services:
  webapp:
    build:
      context: .
      dockerfile: dockerfile
    environment:
      - VITE_OLLAMA_URL=http://localhost:11434
    ports:
      - 3000:80
  ia_server:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    command: serve
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_MODELS=mistral
      - OLLAMA_ORIGINS=*
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]